<a href="https://colab.research.google.com/github/tomersk/learn-python/blob/main/03_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 3.4 Array Manipulation
Often we need to change the array, transpose it, get some elements, or change some elements. This is illustrated by this example, in which first we create the array and then play with it. We have already seen in the previous section, that we can change the value of any element by calling it by the indices, and then assigning new value to it. First, we generate normally distributed random number of size (2×5) to create an array, which we would like to manipulate.

In [2]:
import numpy as np
foo = np.random.randn(2,3)
foo

array([[ 0.36283246,  2.61402225, -1.04827498],
       [-0.49774083, -0.52976937,  0.75586423]])

The array is transposed using T attributes.

In [3]:
foo.T

array([[ 0.36283246, -0.49774083],
       [ 2.61402225, -0.52976937],
       [-1.04827498,  0.75586423]])

We can access some elements of the array, and if we want, new values also can be assigned to them.
In this example, we shall first access element at (0,1) indices, and then we shall replace it by 5.
Finally we will print the variable to check if the variable got modified.

In [4]:
print(foo[0,1])

foo[0,1]=5
print(foo)

2.6140222464576492
[[ 0.36283246  5.         -1.04827498]
 [-0.49774083 -0.52976937  0.75586423]]


The shape of any array is changed by using the reshape method. During reshape operation, the change in number of elements is not allowed. In the following example, first we shall create an
array having size of (3×6), and the we shall change its shape to (2×9).

In [5]:
foo = np.random.randn(3,6)
foo.reshape(2,9)

array([[-0.23974728,  2.15601789, -0.58866054, -0.94078212,  0.1031432 ,
         1.13549013, -0.03180578,  0.70462518, -0.22228889],
       [ 0.88917479, -0.1367948 , -0.07020427,  1.02353006, -0.47758702,
        -0.59042834,  0.08574093,  0.181381  ,  2.86724845]])

Like we can access the any elements of the array and change it, in similar way we can access the any attributes, and modify them. However, the modification is only allowed if the attributes is writeable, and the new value makes some sense to the variable. We can use this behaviour, and change the
shape of variable using the shape attributes.

In [6]:
foo = np.random.randn(4,3)
print(foo.shape)
print(foo)

foo.shape = 2,6
print(foo.shape)
print(foo)

(4, 3)
[[ 0.4771758  -0.76936763 -2.34410875]
 [-0.4262899  -0.66992844 -2.27842671]
 [-0.92889648  1.19237224 -0.59784249]
 [-0.16383886  0.4506501   0.85307605]]
(2, 6)
[[ 0.4771758  -0.76936763 -2.34410875 -0.4262899  -0.66992844 -2.27842671]
 [-0.92889648  1.19237224 -0.59784249 -0.16383886  0.4506501   0.85307605]]


In the above example, first an array is defined with a size of (4×3) and then its shape is assigned a value of (2,6), which makes the array of size (2×6). As we can not change the number of elements, so if we define one dimension of the new variable, second dimension can be computed with ease.

Numpy allow us to define -1 for the default dimension in this case. We can make the desired change in the shape of variable by using default dimension also.

In [7]:
foo.shape = -1,6
print(foo.shape)

(2, 6)


We can flatten the array (make array one dimensional) by using the ravel method, which is explained in the following example:

In [8]:
foo = np.random.rand(2,3)
print(foo)
print(foo.shape)

a = foo.ravel()
print(a.shape)
print(a)

[[0.04943299 0.76016869 0.59526285]
 [0.33552459 0.36886908 0.96542576]]
(2, 3)
(6,)
[0.04943299 0.76016869 0.59526285 0.33552459 0.36886908 0.96542576]
