<a href="https://colab.research.google.com/github/tomersk/learn-python/blob/main/03_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 3.3 Indexing
In this section, we will discuss how to refer to some elements in the numpy array. Remember that in Python first indices is 0. We shall generate some array, say some array whose elements are powered to 3 of the sequence [0,1, ..., 9].

In [2]:
import numpy as np
foo = np.arange(10)**3
foo

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

Print the third item in the array. Third item means we need to put indices as 2.

In [3]:
foo[2]

8

Suppose, we would like to print some sequence of array, say at indices of 2, 3, and 4.

In [4]:
foo[2:5]

array([ 8, 27, 64])

We used 2:5 to get the values at indices of 2, 3 and 4. This is same as saying that foo[np.arange(2,5,1)]. When we do not specify the third value in the indices for array, it is
by default taken as 1. If we want to print value at 2 to 8, with an interval of 3. Now because the
interval is not 1, so we need to define it.

In [5]:
foo[2:10:3]

array([  8, 125, 512])

If we leave the first entry in the index as blank i.e. to get array elements form the beginning of array
with an interval of 2 and upto 6, we issue the following command:

In [6]:
foo[:6:2] # gives the element at 0,2,4

array([ 0,  8, 64])

We get element upto the indices of 4, because arange does not go upto the second argument. We
can use indices also to modify the existing elements in the array, in the same way as we accessed
them. Let us replace the existing value of elements at 0,2 and 4 indices, by -1000.

In [7]:
foo[:6:2] = -1000 # modify the elements at 0,2,4
foo

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

We get the last elements of an array by indices -1. We can also use this to reverse the array, by
giving the increment of -1.

In [8]:
foo[::-1] # reverse an array

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

We can perform the calculation on entire numpy array at once. Suppose we are interested in estimating the square root of the numpy array, we can use sqrt function of numpy library.

In [9]:
np.sqrt(foo) # compute the square root

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,  1.        ,         nan,  5.19615242,         nan,
       11.18033989, 14.69693846, 18.52025918, 22.627417  , 27.        ])

*nan* represents that the element is ‘Not A Number’. 
So when the value of element is negative the output of sqrt become nan. The Warning issued by Python tells that there were some invalid values in the input for which sqrt can not produce any sensible output, and it provides warning (not errors).
In reality, the square root of negative number is complex number, but because we did not define the variable as complex, numpy can not perform operations of complex numbers on this. We need library which handles complex number for such situation.